### ISSUE TITLE
Make repo public

### ISSUE THREAD

**Issue by camina-apps** [camina-apps/Bookworm#112]
- [x] update readme
- [x] add features back from inline checks into GitHub actions serif upload
- [ ] add codecoverage report 
- [ ] add junit results

**Comment by carmen-gh** [comment]
https://github.com/mikepenz/action-junit-report

**Comment by carmen-gh** [comment]
https://github.com/Kotlin/kotlinx-kover
https://github.com/mi-kas/kover-report

https://github.com/marketplace/actions/code-coverage-summary
